BeginningTaskMessage        = "beginning task = %s info input = %v"
TaskErrorMessage            = "task = {} is failed with err = {}"
GetEntityErrorMessage       = "get entity = %s info input = %v fail with err = %v"
UpdateEntityErrorMessage    = "update entity = %s info input = %v fail with err = %v"
CreateEntityErrorMessage    = "create entity = %s info input = %v fail with err = %v"
GetEntityClientErrorMessage = "get entity client = %s info input = %v fail with err = %v"
